spring:
    datasource:
        url: jdbc:mysql://localhost:3306/simple_db
        username: root
        password: 1234567890

    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect

    hibernate:
        ddl-auto: create-drop
    show-sql: true